version: "3.8"
services:
    web: 
        build: .
        ports: 
            - 3000:3000
        networks:
            - web-project
    mongo:
        image: mongo
        ports: 
            - 27017:27017
        networks:
            - web-project
        volumes:
            - ./data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
networks: 
    web-project:
        driver: bridge
